/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package despacho;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel Loaiza
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imagen = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        logo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contraseña = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        usuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        iniciarsesion = new javax.swing.JButton();
        registrarse = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(250, 100));
        setMaximumSize(new java.awt.Dimension(769, 488));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(90, 3, 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        imagen.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 260, 5));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/despacho/image/Diseño sin título (11).jpg"))); // NOI18N
        imagen.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 221, 170));

        fondo.setBackground(new java.awt.Color(0, 0, 0));
        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/despacho/image/Diseño sin título (10).jpg"))); // NOI18N
        fondo.setLabelFor(fondo);
        fondo.setAlignmentY(1.0F);
        fondo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        fondo.setVerifyInputWhenFocusTarget(false);
        imagen.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 490));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        contraseña.setBorder(null);
        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 180, 20));

        jSeparator3.setBackground(new java.awt.Color(90, 3, 3));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 180, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/despacho/image/Group 1lo (2).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 60, 60));

        jSeparator2.setBackground(new java.awt.Color(90, 3, 3));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 180, -1));

        usuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usuario.setToolTipText("");
        usuario.setBorder(null);
        usuario.setCaretColor(new java.awt.Color(204, 204, 204));
        usuario.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 180, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("*** Contraseña ***");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, -1, -1));

        iniciarsesion.setBackground(new java.awt.Color(90, 3, 3));
        iniciarsesion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        iniciarsesion.setForeground(new java.awt.Color(255, 255, 255));
        iniciarsesion.setText("Iniciar Sesión");
        iniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarsesionActionPerformed(evt);
            }
        });
        jPanel1.add(iniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, 30));

        registrarse.setBackground(new java.awt.Color(90, 3, 3));
        registrarse.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        registrarse.setForeground(new java.awt.Color(90, 3, 3));
        registrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrarse.setText("Registrarse");
        registrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 70, -1));

        jSeparator4.setBackground(new java.awt.Color(90, 3, 3));
        jSeparator4.setForeground(new java.awt.Color(90, 3, 3));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 412, 70, 1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/despacho/image/Rectangle 3lo (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaActionPerformed

    private void iniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarsesionActionPerformed
        String usu = usuario.getText();
        String contra= contraseña.getText();
        String sSQL,id ="",contraseña="",perfil="";
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn=mysql.Conectar();
        sSQL="SELECT*FROM usuario WHERE nombre='"+usu+"' and contrasenia='"+contra+"';";
        try{
            Statement st=cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);
            while(rs.next()){
                id=rs.getString("nombre");
                contraseña=rs.getString("contrasenia");
                perfil=rs.getString("rol");
            }
            if (!id.equals("") && !contraseña.equals("")){
                if(perfil.equals("admin")){
                    MenuAdmin va = new MenuAdmin();
                    va.show();
                }
                else{
                    MenUsuario vg=new MenUsuario();
                    vg.show();
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"Usuario no registrado");
                cn.close();
            }
        }
        catch(Exception e){}
    }//GEN-LAST:event_iniciarsesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel imagen;
    private javax.swing.JButton iniciarsesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel registrarse;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
